# Generated by Django 3.1.5 on 2021-03-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20210320_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor_profile',
            options={'verbose_name_plural': 'Doctor`s Profile'},
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Patient Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('admint_date', models.DateTimeField(auto_now_add=True, verbose_name='Admition Date')),
                ('bed_no', models.CharField(max_length=20, verbose_name='Bed No.')),
                ('address', models.TextField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('problem', models.TextField(blank=True, max_length=300)),
                ('patient_father_name', models.CharField(max_length=100, verbose_name='Father`s Name')),
                ('patient_mother_name', models.CharField(max_length=100, verbose_name='Mother`s Name')),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name='Guardian Name')),
                ('guardian_phone_no', models.CharField(blank=True, max_length=11, verbose_name='Guardian`s Phone Number')),
                ('assign_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to='sadmin.doctor_profile')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
