# Generated by Django 3.1.5 on 2021-03-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20210321_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='admint_date',
            new_name='admit_date',
        ),
    ]
