# Generated by Django 3.1.5 on 2021-03-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20210321_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
    ]
