# Generated by Django 3.1.5 on 2021-03-22 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0008_auto_20210321_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Package Name')),
                ('detail', models.TextField(blank=True, max_length=400, verbose_name='Package details')),
                ('price', models.FloatField(default='00', verbose_name='Package Price')),
            ],
            options={
                'verbose_name_plural': ' Packages ',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='sadmin.department'),
        ),
    ]
