# Generated by Django 3.1.5 on 2021-03-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_auto_20210322_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='Department',
            new_name='department',
        ),
    ]
