# Generated by Django 3.1.5 on 2021-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0011_auto_20210322_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(default='00', verbose_name='Package Price'),
        ),
    ]
