# Generated by Django 3.1.5 on 2021-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0012_auto_20210322_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('paid_by', models.CharField(max_length=200, null=True)),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
