# Generated by Django 3.1.5 on 2021-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0014_auto_20210328_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Expenses Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Expense Details',
            },
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Income Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Income Details',
            },
        ),
        migrations.AlterModelOptions(
            name='homerent',
            options={'verbose_name': 'Rent Cost Per Month'},
        ),
    ]
