# Generated by Django 3.1.5 on 2021-03-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0015_auto_20210328_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemodel',
            options={'verbose_name': 'Expense Detail'},
        ),
        migrations.AlterModelOptions(
            name='incomemodel',
            options={'verbose_name': 'Income Detail'},
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_leave',
            field=models.BooleanField(default=False, verbose_name='Leave Patient'),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Salary Payable')),
                ('date', models.DateField(blank=True, verbose_name='Salaray Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid Salary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.employee_profile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Salary',
            },
        ),
        migrations.CreateModel(
            name='DoctorSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Salary Payable')),
                ('date', models.DateField(blank=True, verbose_name='Salary Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid Salary')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.doctor_profile', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Doctor Salary',
            },
        ),
    ]
