# Generated by Django 3.1.5 on 2021-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0017_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.BooleanField(default=False, verbose_name='Finished Appointment'),
        ),
    ]
