# Generated by Django 3.1.5 on 2021-03-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0018_appointment_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.patient', verbose_name='Patient Name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('New Visit', 'New Visit'), ('Renew Visit', 'Renew Visit')], max_length=20, null=True, verbose_name='Visit Type'),
        ),
        migrations.CreateModel(
            name='Doctor_Patient_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(verbose_name='Total Patient')),
                ('date', models.DateTimeField(verbose_name='Visited Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.doctor_profile', verbose_name='Doctor Name')),
            ],
            options={
                'verbose_name': 'Doctor`s total Patient visit',
                'verbose_name_plural': 'Doctor`s total Patient visit',
            },
        ),
    ]
