# Generated by Django 3.1.5 on 2021-03-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0019_auto_20210329_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_patient_count',
            name='total_count',
        ),
    ]
