# Generated by Django 3.1.5 on 2021-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0020_remove_doctor_patient_count_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference By'),
        ),
    ]
