# Generated by Django 3.1.5 on 2021-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0021_auto_20210329_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approve status'),
        ),
        migrations.DeleteModel(
            name='Doctor_Patient_Count',
        ),
    ]
